version: "3.8"
services:
  http-backend:
    build:
      context: sampleserver
    ports:
      - "50051"
  envoy:
    image: envoyproxy/envoy:v1.21.1
    ports:
      - "8080:80"
      - "9901:9901"
    volumes:
      - ./envoy:/etc/envoy:ro
